# : Manager {{{
[manager]
cwd = { fg = "#396ec7" }  # Blue

# Hovered
hovered = { bg = "#444444" }  # Darkened background
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#c62f37", italic = true, underline = true }  # Red
find_position = { fg = "#f2f84a", italic = true }  # Yellow

# Marker
marker_copied = { fg = "#e5e5e5", bg = "#37b378" }  # Light gray on Green
marker_cut = { fg = "#e5e5e5", bg = "#c62f37" }  # Light gray on Red
marker_marked = { fg = "#e5e5e5", bg = "#3ba7cc" }  # Light gray on cyan
marker_selected = { fg = "#e5e5e5", bg = "#f2f84a" }  # Light gray on Yellow

# Tab
tab_active = { bg = "#444444", fg = "#396ec7" }  # Darkened background, Blue text
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "#37b378", bg = "#444444" }  # Green on Darkened background
count_cut = { fg = "#c62f37", bg = "#444444" }  # Red on Darkened background
count_selected = { fg = "#37b378", bg = "#444444" }  # Green on Darkened background

# Border
border_symbol = "│"
border_style = { fg = "#444444" }  # Darkened background

# : }}}

# : Status {{{
[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#396ec7", bg = "#444444" }  # Blue on Darkened background

# Mode
mode_normal = { fg = "#444444", bg = "#396ec7", bold = true }  # Dark gray on Blue
mode_select = { fg = "#444444", bg = "#396ec7", bold = true }  # Dark gray on Blue
mode_unset = { fg = "#444444", bg = "#396ec7", bold = true }  # Dark gray on Blue

# Progress
progress_label = { fg = "#e5e5e5", bold = true }  # Light gray
progress_normal = { fg = "#37b378", bg = "#444444" }  # Green on Darkened background
progress_error = { fg = "#c62f37", bg = "#444444" }  # Red on Darkened background

# Permissions
permissions_t = { fg = "#37b378" }  # Green
permissions_r = { fg = "#c62f37" }  # Red
permissions_w = { fg = "#f2f84a" }  # Yellow
permissions_x = { fg = "#37b378" }  # Green
permissions_s = { fg = "#e5e5e5" }  # Light gray

# : }}}

# : Select {{{
[select]
border = { fg = "#37b378" }  # Green
active = { fg = "#f2f84a", bold = true }  # Yellow
inactive = {}

# : }}}

# : Input {{{
[input]
border = { fg = "#37b378" }  # Green
title = {}
value = {}
selected = { reversed = true }

# : }}}

# : Completion {{{
[completion]
border = { fg = "#37b378" }  # Green

# : }}}

# : Tasks {{{
[tasks]
border = { fg = "#37b378" }  # Green
title = {}
hovered = { fg = "#f2f84a", underline = true }  # Yellow

# : }}}

# : Which {{{
[which]
mask = { bg = "#444444" }  # Darkened background
cand = { fg = "#37b378" }  # Green
rest = { fg = "#e5e5e5" }  # Light gray
desc = { fg = "#f2f84a" }  # Yellow
separator = "  "
separator_style = { fg = "#e5e5e5" }  # Light gray

# : }}}

# : Help {{{
[help]
on = { fg = "#37b378" }  # Green
run = { fg = "#f2f84a" }  # Yellow
hovered = { reversed = true, bold = true }
footer = { fg = "#e5e5e5", bg = "#000000" }  # Light gray on Black

# : }}}

# : Notify {{{
[notify]
title_info = { fg = "#37b378" }  # Green
title_warn = { fg = "#c62f37" }  # Red
title_error = { fg = "#f2f84a" }  # Yellow

# : }}}

# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#f2f84a" },  # Yellow

    # Media
    { mime = "video/*", fg = "#c62f37" },  # Red
    { mime = "audio/*", fg = "#c62f37" },  # Red

    # Archives
    { mime = "application/zip", fg = "#b835bc" },  # Magenta
    { mime = "application/x-tar", fg = "#b835bc" },  # Magenta
    { mime = "application/x-bzip*", fg = "#b835bc" },  # Magenta
    { mime = "application/x-bzip2", fg = "#b835bc" },  # Magenta
    { mime = "application/x-7z-compressed", fg = "#b835bc" },  # Magenta
    { mime = "application/x-rar", fg = "#b835bc" },  # Magenta
    { mime = "application/x-xz", fg = "#b835bc" },  # Magenta

    # Documents
    { mime = "application/doc", fg = "#37b378" },  # Green
    { mime = "application/pdf", fg = "#37b378" },  # Green
    { mime = "application/rtf", fg = "#37b378" },  # Green
    { mime = "application/vnd.*", fg = "#37b378" },  # Green

    # Fallback
    { name = "*", fg = "#e5e5e5" },  # Blue
    { name = "*/", fg = "#396ec7" }  # Blue
]

# : }}}
