#!/bin/sh

# Set config and data folder for nvim, etc...
export XDG_CONFIG_HOME="$HOME"/.XDG/config
export XDG_CACHE_HOME="$HOME"/.XDG/cache
export XDG_DATA_HOME="$HOME"/.XDG/data
export XDG_STATE_HOME="$HOME"/.XDG/state
export XDG_RUNTIME_DIR="$HOME"/.XDG/runtime

# Some global XDG variables
command -v librewolf >> /dev/null && export BROWSER=librewolf
if [ -d /opt/cuda ]; then
	export CUDA_HOME=/opt/cuda
	export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
fi
command -v less >> /dev/null && export LESSHISTFILE="$XDG_STATE_HOME"/less_history
command -v gradle >> /dev/null && export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
command -v java >> /dev/null && export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
command -v gpg >> /dev/null && export GNUPGHOME="$XDG_DATA_HOME"/gnupg
command -v qt5ct >> /dev/null && export QT_QPA_PLATFORMTHEME='qt5ct'
command -v qt6ct >> /dev/null && export QT_QPA_PLATFORMTHEME='qt6ct'
command -v wine >> /dev/null && export WINEPREFIX="$XDG_DATA_HOME"/wine
command -v python >> /dev/null && export PYTHONHISTORY="$XDG_DATA_HOME"/python_history
command -v ipython >> /dev/null && export IPYTHONDIR="$XDG_CONFIG_HOME"/ipython
command -v go >> /dev/null && export GOPATH="$XDG_DATA_HOME"/go
if command -v docker >> /dev/null; then
	export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
	if [ -f /usr/libexec/docker/cli-plugins/docker-compose ] || [ -f /usr/lib/docker/cli-plugins/docker-compose ]; then
		export COMPOSE_BAKE=true
	fi
fi
command -v cargo >> /dev/null && export CARGO_HOME="$XDG_DATA_HOME"/cargo
command -v npm >> /dev/null && export NPM_CONFIG_CACHE="$XDG_CACHE_HOME"/npm
command -v scilab >> /dev/null && export SCIHOME="$XDG_STATE_HOME"/scilab
if command -v adb >> /dev/null; then
	export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
	alias adb='HOME="$XDG_DATA_HOME"/android adb'
fi
command -v node >> /dev/null && export NODE_REPL_HISTORY="$XDG_STATE_HOME"/node_repl_history
export KERAS_HOME="$XDG_STATE_HOME/keras"
command -v wget >> /dev/null && alias wget='wget --hsts-file=$XDG_DATA_HOME/wget-hsts'
command -v nvidia-settings >> /dev/null && alias nvidia-settings='nvidia-settings --config=$XDG_CONFIG_HOME/nvidia/settings'

if test -f "$HOME"/.bashrc; then
	. "$HOME"/.bashrc
fi

if [ -z "$SSH_CONNECTION" ] && [ -z "$TMUX" ] && [ ! "$DISPLAY" ] || [ "$XDG_VTNR" = 8 ] || [ "$(tty)" = /dev/tty1 ]; then
	if command -v startx > /dev/null; then
		startx
	fi
fi
